# Gruvbox material tmux theme

set-option @tmux_theme "gruvbox-material"
set-option status-position top
set-option status on
set-option status-justify left
set-option status-style "bg=#ebdbb2,fg=#1d2021"
set-option status-left-length 100
set-option status-left "#{?client_prefix,#[bg=#d3869b],#[bg=#d8a657]}#[fg=#282828,bold] #S #[bg=#282828] "
set-option status-right-length 400
set-option status-right "#{?#{m:*zed/*,#{session_name}},,#[align=absolute-right]#[bg=#282828] #[bg=#d8a657#,fg=#282828#,bold] #(~/.config/tmux/shorten-path '#{pane_current_path}') }"
# set-option status-right "#[align=absolute-centre,fg=#1d2021,bold]#{?#{==:#T,#H},,#T @ }#(~/.config/tmux/shorten-path '#{pane_current_path}') #[align=right]"
set-option window-status-format "#[fg=#3c3836,bg=#928374] #I:#W "
set-option window-status-current-format "#[bg=#ebdbb2,fg=#1d2021,bold] #I:#W "
set-option window-status-style "fg=#3c3836,bg=#928374"
set-option window-status-current-style "fg=#1d2021,bg=#ebdbb2,bold"
set-option window-status-activity-style "fg=#3c3836,bg=#928374"
set-option window-status-bell-style "fg=#3c3836,bg=#928374"
set-option window-status-last-style "fg=#3c3836,bg=#928374"
set-option window-status-separator ""
set-option message-style "bg=#282828,fg=#ebdbb2"
set-option message-command-style "bg=#282828,fg=#ebdbb2"

run-shell -b 'session="#{session_name}"; tmux list-windows -t "$session" -F "##{window_id}" | while IFS= read -r w; do tmux set-window-option -q -u -t "$w" window-status-format; tmux set-window-option -q -u -t "$w" window-status-current-format; tmux set-window-option -q -t "$w" popup-border-lines heavy; tmux set-window-option -q -t "$w" popup-style "bg=#282828,fg=#ebdbb2"; tmux set-window-option -q -t "$w" popup-border-style "fg=#ebdbb2"; tmux set-window-option -q -t "$w" pane-border-style "fg=#282828"; tmux set-window-option -q -t "$w" pane-active-border-style "fg=#ebdbb2"; tmux set-window-option -q -t "$w" pane-border-status top; tmux set-window-option -q -t "$w" pane-border-indicators both; tmux set-window-option -q -t "$w" pane-border-lines simple; tmux set-window-option -q -t "$w" pane-border-format ""; tmux set-window-option -q -t "$w" mode-style "bg=#d8a657,fg=#1d2021,bold"; done'
