tap "buo/cask-upgrade"
tap "homebrew-zathura/zathura"
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "koekeishiya/formulae"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Language server for beancount files
brew "beancount-language-server"
# Cloudformation templates to Terraform HCL converter
brew "cf2tf"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# C implementation of GitHub Flavored Markdown
brew "cmark-gfm"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Securely send things from one computer to another
brew "croc"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Docker CLI plugin for extended build capabilities with BuildKit
brew "docker-buildx"
# Isolated development environments using Docker
brew "docker-compose"
# Platform keystore credential helper for Docker
brew "docker-credential-helper"
# Validate EPUB files, version 2.0 and later
brew "epubcheck"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Package manager and build system for Fortran
brew "fpm"
# GNU awk utility
brew "gawk"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Highest-quality GIF encoder based on pngquant
brew "gifski"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU implementation of time utility
brew "gnu-time"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Colorize logfiles and command output
brew "grc"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Sort Python imports automatically
brew "isort"
# Command-line note taker
brew "jrnl"
# Generic command-line non-JVM Apache Kafka producer and consumer
brew "kcat"
# VPN kill switch for macOS
brew "killswitch"
# Pager program similar to more
brew "less"
# Input filter for the pager less
brew "lesspipe"
# Sophisticated file transfer program
brew "lftp"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Command-line utility to interact with linkerd
brew "linkerd"
# LLM inference in C/C++
brew "llama.cpp"
# Apple Silicon Monitor Top written in Go Lang
brew "mactop"
# Mac App Store command-line interface
brew "mas"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Deep clean and optimize your Mac
brew "mole"
# Port scanning utility for large networks
brew "nmap"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Package for scientific computing with Python
brew "numpy"
# HTTP load generator, inspired by rakyll/hey with tui animation
brew "oha"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# PAM module for reattaching to the user's GUI (Aqua) session
brew "pam-reattach"
# Convert PDFs to images
brew "pdf2image"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Fast, disk space efficient package manager
brew "pnpm"
# Python package management tool
brew "poetry"
# Object-relational database system
brew "postgresql@16"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Parse HTML at the command-line
brew "pup"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Implementation of Python 3 in Python
brew "pypy3.10"
# Diff filter highlighting which line parts have changed
brew "riff"
# Utility that provides fast incremental file transfer
brew "rsync"
# Rust toolchain installer
brew "rustup"
# SOcket CAT: netcat on steroids
brew "socat"
# Version control system designed to be a better CVS
brew "subversion"
# User interface to the TELNET protocol
brew "telnet"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line tool for sharing terminal over the web
brew "ttyd"
# Syntax-aware linter for prose
brew "vale"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Convert HTML to PDF
brew "weasyprint"
# Internet file retriever
brew "wget"
# Library to create, extract, and modify Windows Imaging files
brew "wimlib"
# Automatic workarounds for problems in Wine
brew "winetricks"
# PDF viewer
brew "homebrew-zathura/zathura/zathura"
# MuPDF backend plugin for zathura
brew "homebrew-zathura/zathura/zathura-pdf-mupdf"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Command-line interface for 1Password
cask "1password-cli"
# Password manager
cask "1password@beta"
# Application uninstaller
cask "appcleaner"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Open-source KVM software
cask "barrier"
# E-books management software
cask "calibre"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Server and cloud storage browser
cask "cyberduck"
# Voice and text chat software
cask "discord"
# Desktop client for Ente Auth
cask "ente-auth"
# Web browser
cask "firefox@beta"
# Screenshot software with built-in annotation tools
cask "flameshot"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome@beta"
# Open-source video transcoder
cask "handbrake-app"
# Free and open-source media player
cask "iina"
# Jellyfin desktop client
cask "jellyfin-media-player"
# Menu bar manager
cask "jordanbaird-ice"
# Open-source screen recorder built with web technology
cask "kap"
# Keyboard customiser
cask "karabiner-elements"
# Preview and audit Kindle eBooks
cask "kindle-previewer"
# Menu bar app for running local LLMs
cask "llamabarn"
# Discover, download, and run local LLMs
cask "lm-studio"
# Extensible two-pane file manager
cask "marta"
# Sandbox construction video game
cask "minecraft"
# Neovim Client
cask "neovide-app"
# Calendar for professionals and teams
cask "notion-calendar"
# Calculator and converter application
cask "numi"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Replacement for Docker Desktop
cask "orbstack"
# Rhythm game
cask "osu"
# VPN client focusing on security
cask "protonvpn"
# Archive manager for data compression and backups
cask "rar"
# Control your tools with a few keystrokes
cask "raycast"
# Open source virtual/remote desktop application
cask "rustdesk"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack@beta"
# System monitor for the menu bar
cask "stats"
# Video game digital distribution service
cask "steam"
# To-do list
cask "todoist-app"
# Multimedia player
cask "vlc"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm@nightly"
# REST, GraphQL and gRPC client
cask "yaak"
# Multiplayer code editor
cask "zed"
# Video communication and virtual meeting platform
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Balatro", id: 6502451661
mas "Cult Of The Lamb", id: 1639580858
mas "Gifski", id: 1351639930
mas "Grila", id: 6444335028
mas "JapaneseLife", id: 1634749545
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PowerWash Simulator", id: 6477445344
mas "rcmd", id: 1596283165
mas "Sasquatch", id: 1465346522
mas "Save to Reader", id: 1640236961
mas "Shareful", id: 1522267256
mas "UTC Time", id: 1538245904
mas "Xcode", id: 497799835
go "github.com/wadey/gocovmerge"
go "github.com/golangci/golangci-lint/cmd/golangci-lint"
go "github.com/uber-go/gopatch"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "gotest.tools/gotestsum"
go "github.com/go-enry/go-license-detector/v4/cmd/license-detector"
go "github.com/vektra/mockery/v2"
go "github.com/golang/mock/mockgen"
go "github.com/goware/modvendor"
go "github.com/tinylib/msgp"
go "github.com/golang/protobuf/protoc-gen-go"
go "github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto"
go "github.com/favadi/protoc-go-inject-tag"
go "github.com/stormcat24/protodep"
go "github.com/frapposelli/wwhrd"
