tap "artginzburg/tap"
tap "aws/tap"
tap "buo/cask-upgrade"
tap "deviceinsight/packages"
tap "felixkratz/formulae"
tap "hashicorp/tap"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "localsend/localsend"
tap "peak/tap"
tap "rcmdnk/file"
# Official Amazon AWS command-line interface
brew "awscli"
# Curl like simplicity to access AWS resources
brew "awscurl"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Securely send things from one computer to another
brew "croc"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Docker CLI plugin for extended build capabilities with BuildKit
brew "docker-buildx"
# Isolated development environments using Docker
brew "docker-compose"
# Platform keystore credential helper for Docker
brew "docker-credential-helper"
# Validate EPUB files, version 2.0 and later
brew "epubcheck"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Collection of GNU find, xargs, and locate
brew "findutils"
# GNU awk utility
brew "gawk"
# Highest-quality GIF encoder based on pngquant
brew "gifski"
# Audit git repos for secrets
brew "gitleaks"
# GNU implementation of time utility
brew "gnu-time"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Go implementation of configuration language for defining JSON data
brew "go-jsonnet"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Colorize logfiles and command output
brew "grc"
# Like cURL, but for gRPC
brew "grpcurl"
# Kubernetes package manager
brew "helm"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Improved top (interactive process viewer)
brew "htop"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Sort Python imports automatically
brew "isort"
# Package manager for Jsonnet
brew "jsonnet-bundler"
# VPN kill switch for macOS
brew "killswitch"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Package manager for kubectl plugins
brew "krew"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Pager program similar to more
brew "less"
# Input filter for the pager less
brew "lesspipe"
# Terminal file manager
brew "lf"
# Command-line utility to interact with linkerd
brew "linkerd"
# Apple Silicon Monitor Top written in Golang
brew "mactop"
# Mac App Store command-line interface
brew "mas"
# Port scanning utility for large networks
brew "nmap"
# Tiny, lightning fast, feature-packed file manager
brew "nnn"
# Platform built on V8 to build network applications
brew "node"
# Package for scientific computing with Python
brew "numpy"
# Manage multiple Node.js versions
brew "nvm"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Convert PDFs to images
brew "pdf2image"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Object-relational database system
brew "postgresql@16"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Implementation of Python 3 in Python
brew "pypy3.10"
# Persistent key-value database, with built-in net interface
brew "redis"
# Diff filter highlighting which line parts have changed
brew "riff"
# Terminal based presentation tool
brew "slides"
# Version control system designed to be a better CVS
brew "subversion"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# User interface to the TELNET protocol
brew "telnet"
# Terraform version manager inspired by rbenv
brew "tfenv"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line tool for sharing terminal over the web
brew "ttyd"
# Syntax-aware linter for prose
brew "vale"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Automatic workarounds for problems in Wine
brew "winetricks"
# Permanent TouchID support for sudo
brew "artginzburg/tap/sudo-touchid"
# EC2 Instance Selector is a tool to filter EC2 instance types based on resource criteria
brew "aws/tap/ec2-instance-selector"
# A Commandline interface for Apache Kafka which provides useful features adapted from kubectl for Kubernetes.
# Multiple kafka brokers can be configured in a config file and the active broker is also persisted within the config.
# In addition kafkactl supports auto-completion for its commands as well as topic names.
brew "deviceinsight/packages/kafkactl"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# Vault
brew "hashicorp/tap/vault"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Parallel S3 and local filesystem execution tool
brew "peak/tap/s5cmd"
# Command-line interface for 1Password
cask "1password-cli"
# Password manager
cask "1password@beta"
# Privacy-focused app for managing your finances
cask "actual"
# Application uninstaller
cask "appcleaner"
# Open-source KVM software
cask "barrier"
# E-books management software
cask "calibre"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Voice and text chat software
cask "discord"
# Desktop client for Ente Auth
cask "ente-auth"
# Screenshot software
cask "flameshot"
# GitHub notifications on your menu bar
cask "gitify"
# Web browser
cask "google-chrome@beta"
# Jellyfin desktop client
cask "jellyfin-media-player"
# Menu bar manager
cask "jordanbaird-ice"
# Open-source screen recorder built with web technology
cask "kap"
# Keyboard customiser
cask "karabiner-elements"
# Preview and audit Kindle eBooks
cask "kindle-previewer"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Sandbox construction video game
cask "minecraft"
# Web browser focused on privacy and on minimizing tracking and fingerprinting
cask "mullvad-browser"
# VPN client
cask "mullvadvpn@beta"
# Calendar for professionals and teams
cask "notion-calendar"
# Calculator and converter application
cask "numi"
# Rhythm game
cask "osu"
# Home media player
cask "plex"
# Archive manager for data compression and backups
cask "rar"
# Control your tools with a few keystrokes
cask "raycast"
# Open source virtual/remote desktop application
cask "rustdesk"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack@beta"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# To-do list
cask "todoist"
# Web browser focusing on security
cask "tor-browser"
# Multimedia player
cask "vlc"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm@nightly"
# Network protocol analyzer
cask "wireshark"
# View output from scripts in the menu bar
cask "xbar"
# Multiplayer code editor
cask "zed"
# Video communication and virtual meeting platform
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Endel", id: 1346247457
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "Grila", id: 6444335028
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Shareful", id: 1522267256
mas "UTC Time", id: 1538245904
