#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config debug_output          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0
yabai -m config window_animation_frame_rate  120
# yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config window_border_hidpi          off
yabai -m config window_border_blur           on
yabai -m config active_window_border_color 0xffe1e3e4
# yabai -m config normal_window_border_color 0xff555555
yabai -m config normal_window_border_color 0xff2a2f38
yabai -m config insert_feedback_color      0xff9dd274
# yabai -m config active_window_border_color   0xff8E83B8
# yabai -m config normal_window_border_color   0xff8E83B8
# yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize
# yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   6

function create_space {
  space_exists=$(yabai -m query --spaces --space "$1")
  if [ -z "$space_exists" ]; then
    yabai -m space --create
  fi

  yabai -m space "$1"
}

# for i in {1..8}; do
#     create_space "$i"
# done

yabai -m rule --add label="Finder" app="^Finder$" title=".*" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off layer=above
yabai -m rule --add label="Raycast" app="^Raycast$" title=".*" manage=off layer=above
yabai -m rule --add label="Shottr" app="^Shottr$" title=".*" manage=off layer=above
# yabai -m rule --add label="Firefox" app="^Firefox$" title="^Opening.*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Raycast" app="Raycast" title=".*" manage=off layer=above
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Bartended" app="Bartended" title=".*" manage=off layer=above
yabai -m rule --add label="Gitify" app="Gitify" title=".*" manage=off layer=above sticky=on
# yabai -m rule --add label="Kitty blur" app="kitty" border=on

yabai -m signal --add app="Notion Calendar" event="window_focused" \
    action="CRON_WINDOW_ID=$(yabai -m query --windows | jq '.[] | select(.app == "Notion Calendar") | .id') | yabai -m window $CRON_WINDOW_ID --ratio abs:0.66 | yabai -m window $CRON_WINDOW_ID --swap east"

create_space 1
yabai -m rule --add app="WezTerm" space=1

# 2 and 3 is for firefox
create_space 2
create_space 3

create_space 4
yabai -m rule --add app="Slack" space=4

create_space 5
yabai -m rule --add app="Spotify" space=5

create_space 6
yabai -m rule --add app="Obsidian" space=6

create_space 7
yabai -m rule --add app="(Notion Calendar|Todoist)" space=7 manage=on

create_space 8
yabai -m rule --add app="Discord" space=8

yabai -m rule --apply

open -a WezTerm
open -a Firefox
open -a Slack
open -a Spotify
open -a Obsidian
open -a Todoist
open -a "Notion Calendar"
open -a Discord

# Clean up empty spaces with no windows on them.
# yabai -m signal --add event=space_changed action="sh ~/.config/yabai/clean_empty_spaces.sh"

echo "yabai configuration loaded.."
# borders &
