#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
# yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config window_border_hidpi          off
yabai -m config window_border_blur           on
yabai -m config active_window_border_color 0xffe1e3e4
# yabai -m config normal_window_border_color 0xff555555
yabai -m config normal_window_border_color 0xff2a2f38
yabai -m config insert_feedback_color      0xff9dd274
# yabai -m config active_window_border_color   0xff8E83B8
# yabai -m config normal_window_border_color   0xff8E83B8
# yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize
# yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       stack
# yabai -m config top_padding                  12
# yabai -m config bottom_padding               12
# yabai -m config left_padding                 12
# yabai -m config right_padding                12
# yabai -m config window_gap                   06

yabai -m rule --add label="Finder" app="^Finder$" title=".*" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Firefox" app="^Firefox$" title="^Opening.*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Zoom" app="Zoom" title=".*" manage=off
# yabai -m rule --add label="Kitty blur" app="kitty" border=on

echo "yabai configuration loaded.."
