# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
---
gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#f9f5d7"
      - bold

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#a89984"

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#f9f5d7"
      - bold

    # Color of keybindings help text in the bottom line
    # optionsTextColor:
    #   - blue

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#3c3836"
      - bold

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "#fb4934"
      - bold

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#1d2021"

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "#fb4934"
      - bold

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#1d2021"

    # Color for file with unstaged changes
    unstagedChangesColor:
      - "#fb4934"

    # Default text color
    defaultFgColor:
      - default
  mouseEvents: false
  skipDiscardChangeWarning: true
  skipRewordInEditorWarning: true
  sidePanelWidth: 0.2
  expandFocusedSidePanel: true
  showBottomLine: false
  showPanelJumps: false
  nerdFontsVersion: "3"
  filterMode: "fuzzy"
git:
  paging:
    colorArg: always
    pager: delta --paging=never
  commit:
    signOff: true
  skipHookPrefix: ""
  branchLogCmd: 'git log --color=always --stat --graph --date=human --pretty=lc {{branchName}} --'
  allBranchesLogCmd: 'git log --color=always --graph --date=human --pretty=lc --all'
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  openDirInEditor: "nvim {{filename}}"
notARepository: "skip"
customCommands:
  - key: '<c-p>'
    description: "Pull from a specific remote repository"
    context: 'global'
    loadingText: 'Pulling ...'
    prompts:
      - type: 'menuFromCommand'
        title: 'Which branch to pull from?'
        command: bash -c "git branch -r"
        filter: '(?P<remote>[a-z0-9-]*)/(?P<branch>[a-z0-9-/]*)\s?.*'
        valueFormat: '{{ .remote }} {{ .branch }}'
        labelFormat: '{{ .remote | bold | cyan }}/{{ .branch | cyan }}'
    command: "git pull {{ index .PromptResponses 0 }}"
  - key: 'f'
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: 'commitFiles'
    description: 'Compare (difftool) with local copy'
  - key: "v"
    context: "localBranches"
    loadingText: "Checking out GitHub Pull Request..."
    command: "gh pr checkout {{.Form.PullRequestNumber}}"
    prompts:
      - type: "menuFromCommand"
        title: "Which PR do you want to check out?"
        key: "PullRequestNumber"
        command: >-
          gh pr list --json number,title,headRefName,updatedAt
          --template '{{`{{range .}}{{printf "#%v: %s - %s (%s)\\n" .number .title .headRefName (timeago .updatedAt)}}{{end}}`}}'
        filter: '#(?P<number>[0-9]+): (?P<title>.+) - (?P<ref_name>[^ ]+).*'
        valueFormat: '{{.number}}'
        labelFormat: '{{"#" | black | bold}}{{.number | white | bold}} {{.title | yellow | bold}}{{" [" | black | bold}}{{.ref_name | green}}{{"]" | black | bold}}'
