gui:
  sidePanelWidth: 0.2
  showCommandLog: false
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: always
    pager: delta --paging=never --navigate --features villsau-lg
  commit:
    signOff: true
  branchLogCmd: 'git log --color=always --stat --graph --date=human --pretty=lc {{branchName}} --'
  allBranchesLogCmd: 'git log --color=always --graph --date=human --pretty=lc --all'
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
customCommands:
  - key: '<c-p>'
    description: "Pull from a specific remote repository"
    context: 'global'
    loadingText: 'Pulling ...'
    prompts:
      - type: 'menuFromCommand'
        title: 'Which branch to pull from?'
        command: bash -c "git branch -r"
        filter: '(?P<remote>[a-z0-9-]*)/(?P<branch>[a-z0-9-/]*)\s?.*'
        valueFormat: '{{ .remote }} {{ .branch }}'
        labelFormat: '{{ .remote | bold | cyan }}/{{ .branch | cyan }}'
    command: "git pull {{ index .PromptResponses 0 }}"

