gui:
  sidePanelWidth: 0.2
  showCommandLog: false
  theme:
    activeBorderColor:
      - '#f2cdcd'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#45475a'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f2cdcd'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
git:
  paging:
    colorArg: always
    pager: delta --paging=never --navigate --features villsau-lg
  commit:
    signOff: true
  branchLogCmd: 'git log --color=always --stat --graph --date=human --pretty=lc {{branchName}} --'
  allBranchesLogCmd: 'git log --color=always --graph --date=human --pretty=lc --all'
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
customCommands:
  - key: '<c-p>'
    description: "Pull from a specific remote repository"
    context: 'global'
    loadingText: 'Pulling ...'
    prompts:
      - type: 'menuFromCommand'
        title: 'Which branch to pull from?'
        command: bash -c "git branch -r"
        filter: '(?P<remote>[a-z0-9-]*)/(?P<branch>[a-z0-9-/]*)\s?.*'
        valueFormat: '{{ .remote }} {{ .branch }}'
        labelFormat: '{{ .remote | bold | cyan }}/{{ .branch | cyan }}'
    command: "git pull {{ index .PromptResponses 0 }}"
  - key: 'f'
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: 'commitFiles'
    description: 'Compare (difftool) with local copy'
  - key: "v"
    prompts:
      - type: 'input'
        title: 'PR id:'
    command: "gh pr checkout {{index .PromptResponses 0}}"
    context: "localBranches"
    loadingText: "checking out PR"
